### ISSUE TITLE
TypeError: Object [object Object] has no method 'helpers'

### ISSUE THREAD

**Issue by ipstas** [dburles/meteor-collection-helpers#18]
I have tried to put your example in the /lib/joins.js and app crashes. Am I missing something obvious?

meteor 1.0, package was installed with meteor add

Thanks

**Comment by jjman505** [comment]
I'm getting this same error. Package list:

accounts-password           1.0.5  Password support for accounts
autopublish                 1.0.2  Publish the entire database to all clients
dburles:collection-helpers  1.0.2  Transform your collections with helpers that you define
fourseven:scss              1.0.0  Style with attitude and autoprefixer.
insecure                    1.0.2  Allow all database writes by default
iron:router                 1.0.6  Routing specifically designed for Meteor
meteor-platform             1.2.1  Include a standard set of Meteor packages in your app
natestrauser:font-awesome   4.2.0_1  Latest version Font-Awesome loaded via CDN
reywood:bootstrap3-sass     3.3.0_2  Bootstrap 3 with Sass support
rubaxa:sortable             1.0.0_1  Sortable: reactive minimalist reorderable drag-and-drop lists on modern browsers and touch devices
stevezhu:lodash             1.0.2  A utility library delivering consistency, customization, performance, & extras.
u2622:persistent-session    0.2.1  Persistently store Session data on the client

load order in .meteor/packages has dburles:collection-helpers listed last.

**Comment by dburles** [comment]
hey @jjman505 does the error appear on the server? could you try run the tests just out of interest. `meteor test-packages dburles:collection-helpers`

**Comment by jjman505** [comment]
Yes, the error appears on the server. Curiously enough, that command returns this message:

=> Errors while collecting tests:             
                                              
While trying to test package `dburles:collection-helpers`:
error: Not a known local package, cannot test

**Comment by jjman505** [comment]
Sure, check out this repository: https://github.com/Productiv/productiv-meteor/tree/collection-helpers

**Comment by dburles** [comment]
@jjman505 Thanks! So i've had a look into it, the issue was caused by [dburles:mongo-collection-instances](https://atmospherejs.com/dburles/mongo-collection-instances) (ironically my own code!) which was a dependency of [rubaxa:sortable](https://atmospherejs.com/rubaxa/sortable). The latest version of mongo-collection-instances (0.2.6) doesn't cause any conflict. [I've submit a PR](https://github.com/RubaXa/Sortable/pull/212).

**Comment by dburles** [comment]
Now I'm wondering if @ipstas issue is caused by the same thing but through another package... :neutral_face:

**Comment by jjman505** [comment]
Okay, thanks a bunch! Hopefully they'll get that PR in soon.

**Comment by dburles** [comment]
@jjman505 the PR has gone through :)

**Comment by jjman505** [comment]
Awesome, thanks!

**Comment by dburles** [comment]
@ipstas I believe the issue you were having was caused by houston:admin, please update your project as the bug has been patched
