### ISSUE TITLE
Maximum Collection Supported

### ISSUE THREAD

**Issue by ralphievolt** [dburles/meteor-collection-helpers#23]
What is the maximum collection I can join together with this package? I have 6 collection which are referenced with each other. Can I used it?

**Comment by dburles** [comment]
Hey @ralphievolt that should be fine

**Comment by ralphievolt** [comment]
To further explain my requirement which I'm struggling right now. Here's my collection
collection 1= AA-BB
collection 2= BB-CC
collection 3= CC-DD
collection 4= DD-EE
collection 5= EE-FF

I want to show all the relationship from collection 1 up to collection 5 in a table like this

FF | EE | DD | CC | BB | AA
------------ | ------------- | ------------- | ------------- | ------------- | -------------
F1 | E1 | D1 | C1 | B1 | A1
F2 | E2 | D2 | C2 | B2 | A2

The reason I wrote here so that other can see whether this is doable with the package or not.

**Comment by dburles** [comment]
sure, I don't see why not?

**Comment by ralphievolt** [comment]
I can successfully show the relationship between collection 1 & 2.. How do I pass the relationship now from collection 1 to collection 3?

**Comment by ralphievolt** [comment]
Here's how wrote my code: =)
``` javascript
PalletAggregation .helpers({
  bBoxes: function(){
    return BundleboxAggregation.findOne(this.bundlebox);
  }
});

BundleboxAggregation.helpers({
  bundleboxCode: function(){
    return this.bundlebox;
  },
  sBoxes: function() {
    return ShippingboxAggregation.findOne(this.shippingbox);
  }
})

ShippingboxAggregation.helpers({
  shippingboxCode: function(){
    return this.shippingbox;
  },

})


Template.aggregationReport.helpers({
  palletData: function(){
    return PalletAggregation.find();
  }
});
```

My html template
```html
{{#each palletData}}
  <li> {{palletcode}}   >
    {{bBoxes.bundleboxCode}}   >
    {{sBoxes.shippingboxCode}}   >
  </li>
{{/each}}
```

**Comment by dburles** [comment]
You can just chain them, `foo.helperOne.helperTwo.helperThree`

**Comment by ralphievolt** [comment]
I'm sorry but how do I apply that in my code I pasted above?

**Comment by ralphievolt** [comment]
Where should I place this? is it inside ``` " (this.here) " ``` or ```" return "here"  ``` ?

I am sorry if I bothered you so much =)

**Comment by dburles** [comment]
Here's an example of a more complex structure, hopefully the relationships between authors, books and publishers is easy enough to understand.

```js
Books = new Mongo.Collection('books');
Authors = new Mongo.Collection('authors');
Publishers = new Mongo.Collection('publishers');

Books.helpers({
  author: function() {
    return Authors.findOne(this.authorId);
  },
  publisher: function() {
    return Publishers.findOne(this.publisherId);
  }
});

Authors.helpers({
  books: function() {
    return Books.find({ authorId: this.authorId });
  },
  publishers: function() {
    return Publishers.find({
      _id: { $in: _.pluck(this.books.fetch(), 'publisherId') }});
  }
});

Publishers.helpers({
  books: function() {
    return Books.find({ publisherId: this._id });
  },
  authors: function() {
    return Authors.find({
      _id: { $in: _.pluck(this.books().fetch(), 'authorId') }});
  }
});
```

**Comment by ralphievolt** [comment]
it make sense to me now. Thank you very much
