### ISSUE TITLE
Compatibility with check

### ISSUE THREAD

**Issue by erasaur** [dburles/meteor-collection-helpers#24]
Collection helpers seems to add a special prototype to documents, meaning a test like `check(doc, Object)` on a doc from a `findOne` call would unexpectedly fail. Is there a better way to do checking on documents besides explicitly checking individual keys?

**Comment by dburles** [comment]
Hey @erasaur where exactly are you running the `check`'s? If it's within allow/deny hooks for example you can pass the option `transform: null`.

**Comment by erasaur** [comment]
I'm running them in some `Meteor.methods`.

**Comment by dburles** [comment]
@erasaur you can pass `transform: null` within the `findOne` query like so: `Foo.findOne({}, { transform: null });

**Comment by erasaur** [comment]
@dburles Oh awesome. Thanks!
