### ISSUE TITLE
Why not transform?

### ISSUE THREAD

**Issue by matteodem** [dburles/meteor-collection-helpers#25]
Great package!

I wanted to ask you if there is any specific reason for not using the transform method to apply those helpers. I had a lot of problems when trying to inherit data because functions are not inherited through template instances.

**Comment by dburles** [comment]
Hey thanks @mattoedem but the package does use the transform method!  What was the problem you were having with template instances?

**Comment by matteodem** [comment]
Sorry for not answering, I thought of using the "transform" function for the collection, see here: http://docs.meteor.com/#/full/mongo_collection

**Comment by dburles** [comment]
That's exactly how this package applies the helper methods, by making use of Meteor's collection transform option

**Comment by matteodem** [comment]
Oh god, yes I meant that it doesn't apply functions but rather the values of the helpers. This gets problematic for example when you want to access data inside of child templates with the helpers, which is not possible since the data doesn't inherit functions.

**Comment by dburles** [comment]
Hey might you have an example of what you're describing?

**Comment by matteodem** [comment]
```javascript
test = new Meteor.Collection('test');

test.helpers({
  testField: function () {
    return this.name;
  }
});

test.insert({ name: 'test' });

Template.parent.helpers({
  document: function () {
    return test.find();
  }
});
```

```html
<body>
  {{> parent}}
</body>

<template name="parent">
  {{#each document}}
     {{> child}}
  {{/each}}
</template>


<template name="child">
  {{testField}}
</template>
```

I wrote this on top of my head, but the testField that's being output in the child will be empty.

**Comment by dburles** [comment]
That works just fine :) maybe there's something else going on?

**Comment by matteodem** [comment]
I changed the example, does this also work?

**Comment by dburles** [comment]
In that case `{{field}}` will equal the result of calling the `testField` method.
