### ISSUE TITLE
Performance collection-helpers vs denormalization

### ISSUE THREAD

**Issue by webyak** [dburles/meteor-collection-helpers#28]
Is there any difference regarding performance? I think mongo would be happy if it doesn't need to store duplicates. But how does it look like regarding reactivity and only publishing certain fields?

Big thanks :)

**Comment by dburles** [comment]
Hey @webyak all this package does is allow you to define some prototypical methods for a document instance, I think you might be thinking about two different things!

**Comment by dburles** [comment]
Though I may have misinterpreted you, regarding denorm vs publishing more data, it comes down to the use-case, sometimes it's better to de-norm, most of the time you can just write publications to provide the data any collection relationships require

**Comment by webyak** [comment]
You're right! I have no clue how I came on the idea to skip the whole publishing part. I ended up doing quite some research about joins vs de-norm and bought the whole bulletproof meteor package. So this should clear out every confusion. Thanks David!
