### ISSUE TITLE
how to find all Book with Author condition?

### ISSUE THREAD

**Issue by yuomtheara** [dburles/meteor-collection-helpers#29]
I would like to find all `Book` that `Author` condition of `gender = "Male"`.
```
books: function () {
        return Books.find({
            "author.gender": 'M'
        });
    }
```
pl help me.

**Comment by dburles** [comment]
```js
books: function() {
  var authorIds = Authors.find({ gender: 'M' }).map(function(author) { return author._id. });
  return Books.find({ authorId: { $in: authorIds }});
}
```

**Comment by yuomtheara** [comment]
very thanks. I come from MySQL, so i think it is slow.

**Comment by yuomtheara** [comment]
could create `view` like `MySQL View` or have good solution for this?

**Comment by dburles** [comment]
I think you should just learn about MongoDB. The docs are quite good if you're coming from an SQL background, see here: http://docs.mongodb.org/manual/reference/sql-comparison/
