### ISSUE TITLE
How to write tests using collection helpers?

### ISSUE THREAD

**Issue by MasahiroMorita** [dburles/meteor-collection-helpers#30]
Hi there, I'm coming from Ruby on Rails.
collection helpers are really similar idea with RoR's active models. it's very convenient to write complex data operations into one same place.

however, I'm trying to write test code using jasmine or other meteor test framework, such as MUnit, Tinytest, and gagarin, but I can't be achieved. 

For example, collection A has many related collection B's records and I centralize the creation of B's record in the collection A's helper, I can write:
```
A = new Mongo.Collection('a');
B = new Mongo.Collection('b');
A.helpers({
  createB: function(params) {
    params.parent = this._id;
    return B.insert(params);
  },
  listB: function() {
    return B.find({parent: this._id});
  }
});
````
This case, I should write test like:
```
describe('A', function() {
  var a1;
  beforeAll(function() {
    a1 = A.insert({name: 'first A'});
  }
  it('shoud have many Bs', function() {
    expect(a1.listB.count()).toBe(0);
    a1.createB({name: 'b1'});
    expect(a1.listB.count()).toBe(1);
  }
}
```

**Comment by dburles** [comment]
Hey there shouldn't be any problem writing tests like this. In your example you're not calling listB as a function. Not sure if that's your issue. It should be a1.listB().count()

**Comment by pfkurtz** [comment]
Related question: how do you access collection helpers for writing unit tests? So that I could do something like this:

    var taskHelper = Tasks.__helpers.taskHelper;
    taskHelper.apply({ /* eg, a task object to use as this (the document) */ });

This doesn't seem possible, with the helpers only accessible from a document's prototype, and so we would be forced to write integration tests instead of unit tests, even when we want to just test the function... Or am I missing something? Thanks.

**Comment by dburles** [comment]
Very similar question was posted just recently I believe the answer to be what you're looking for https://github.com/dburles/meteor-collection-helpers/issues/31#issuecomment-85126909

**Comment by pfkurtz** [comment]
Thanks, David, that's just what I'm looking for.

**Comment by dburles** [comment]
Great!  I'll defiantly update the docs as others will likely wish to do the same thing

**Comment by MasahiroMorita** [comment]
Thanks, dburles. Finally, I pass the test.
The point was place the test in server/integration directory, instead of server/unit.
In jasmine's unit test, access to collections is encapsulated by stubs. That's why my test doesn't work.

**Comment by dburles** [comment]
Oh great, good to know
