### ISSUE TITLE
Collection helpers not working with Jasmine test environment

### ISSUE THREAD

**Issue by petr-kalinin** [dburles/meteor-collection-helpers#32]
It seems that in Jasmine test environment, if I set helpers for several collections, some helpers are lost. 

I have created a test repository: https://github.com/petr-kalinin/meteor-collection-name-missing . If you clone it and start Meteor, you will see in browser's console the output like
```
collection-helpers: collection name: foo
collection-helpers: collection name: bar
Foo name: foo
Bar name: bar
Foo whoami: Foo
Foo foo: Foo:foo
Bar whoami: Bar
Bar bar: Bar::bar
```
which is the expected output.

However, the (only) test is not passed. Moreover, if you start Meteor with
`DEBUG=1 JASMINE_DEBUG=1 VELOCITY_DEBUG=1 VELOCITY_DEBUG_MIRROR=1 meteor`
and, after the startup, change the test file to have tests rerun, you will see in the terminal the following output:
```
I20150327-22:30:50.705(3)? [sanjo:jasmine]: loading source file: /home/petr/meteor-univ/jasmine-collection-name/lib/dburles:collection-helpers.js
I20150327-22:30:50.708(3)? [sanjo:jasmine]: loading source file: /home/petr/meteor-univ/jasmine-collection-name/collections/foobar.coffee
I20150327-22:30:50.750(3)? collection-helpers: collection name: undefined
I20150327-22:30:50.750(3)? collection-helpers: collection name: undefined
I20150327-22:30:50.750(3)? Foo name: undefined
I20150327-22:30:50.750(3)? Bar name: undefined
I20150327-22:30:50.751(3)? Foo whoami: Bar
W20150327-22:30:50.752(3)? (STDERR) [sanjo:jasmine]: The code has syntax errors. [TypeError: Object [object Object] has no method 'foo']
```

which is not the expected output, the output identical to the one in the browser console is expected.

I have added a debug output into `dburles:collection-helpers.js` file (see in the repository), and it seems that in normal run, the `_name` field of a collection is set properly, while in Jasmine it is `undefined` for every collection. As a result, all collections share the same element in `Document` array, which leads to this strange behavior. In particular in my case, `Foo` helpers are simply overwritten by `Bar` helpers.

I do not know whether this is a problem of this package, or of Jasmin and/or Velocity.

(A separate issue is that I had to copy the `dburles:collection-helpers.js` file from package to the local `lib` directory not only to add debug output, but also to have Jasmine even see it.)

**Comment by dburles** [comment]
Hey @petr-kalinin I'm not sure exactly what's going wrong there but I'd suggest opening this issue over here https://github.com/meteor-velocity/velocity

**Comment by dburles** [comment]
Btw, just updated the package to not require a reference to `_name`, that might help your tests.

**Comment by petr-kalinin** [comment]
Thanks, it works for me!
