### ISSUE TITLE
Allow helpers with find(), not only findOne()

### ISSUE THREAD

**Issue by hamoid** [dburles/meteor-collection-helpers#33]
Would it be possible to use helpers with find() ?

The reason to do that, in my case, is that I need to transform the results of find() into an array I can feed into a select input, grabbing the id and a name.

That was the first thing I tried to do with meteor-collection-helpers, and it didn't work, then I realized all the examples used findOne(). If it doesn't make sense, maybe the docs could mention that the helper is  available via findOne() only.

**Comment by hamoid** [comment]
An example:

    var opts = Statuses.find().getOptions(Session.get('currLang').code);

and

    Statuses.helpers({
      getOptions: function(langCode) {
        return this.map(function(el) {
          return { id: el._id, name: el.name[langCode] };
        });
      }
    });

**Comment by dburles** [comment]
The helpers are on the documents returned by the find. So what you're looking for could be written as:

 var opts = Foo.find().map(function(doc) { return doc.getOptions(Session.get('foo')); }); 

getOptions: function(langCode) {
  return { id: this._id, name: this.name[langCode] };
}

**Comment by dburles** [comment]
The transformation function is applied to the the *results* of the query, not onto the query cursor itself.  [See here](http://docs.meteor.com/#/full/mongo_collection) under transform.

**Comment by hamoid** [comment]
Thanks. I think I prefer as I have it now with less function calls, even if code may be duplicated when this is used several times:

    var lang = Session.get('currLang').code;
    var opts = Foo.find().map(function(doc) { return { id: doc._id, name: doc.name[lang]}; }); 

Maybe another option would be to augment the collection, as ```Foo.getOptions(lang)```...

In any case, since I got the idea wrong at the beginning, maybe the readme could make it more obvious that what gets new behaviour is each item, and not the collection? Cheers!
