### ISSUE TITLE
Question: Nested Helpers

### ISSUE THREAD

**Issue by boustanihani** [dburles/meteor-collection-helpers#34]
Consider the following snippets from https://github.com/aldeed/meteor-collection2#attach-a-schema-to-meteorusers
```javascript
Schema.UserProfile = new SimpleSchema({
    //...
    firstName: {
        type: String,
        label: 'First name',
        denyUpdate: true,
    },
    lastName: {
        type: String,
        label: 'Last name',
        denyUpdate: true,
    },
    //...
});

Schema.User = new SimpleSchema({
    //...
    profile: {
        type: Schema.UserProfile,
        optional: true
    },
    //...
});

Meteor.users.attachSchema(Schema.User);
```

Is it possible to attach a nested ```fullName``` helper to user profiles, so that:
```
user.profile.fullName = user.profile.firstName + ' ' + user.profile.lastName
```

This was only an example, but when dealing with large complex object structures, one may like to group and nest helpers for organizational needs... Is this possible using this package?

**Comment by dburles** [comment]
The short answer is no, but an interesting idea.

**Comment by boustanihani** [comment]
I'm glad you see it this way :)

**Comment by zimme** [comment]
Doesn't this work?
```js
Meteor.users.helpers({
  'profile.fullName': function () {
    return this.profile.firstName + ' ' + this.profile.lastName;
  }
});
```

**Comment by stfnbrgh** [comment]
Hi, I needed nested helpers as well so I implemented them. They can be used on embedded documents (directly and within arrays). I Intentionally only logged errors instead of throwing as I'm still unsure when It needs to fail hard. 

https://github.com/dburles/meteor-collection-helpers/pull/37

**Comment by zimme** [comment]
How about creating a separate package named "nested-collection-helpers" or something which uses this package as a dependency and add the nesting feature?

**Comment by boustanihani** [comment]
@stfnbrgh Is it hard to merge your code into this package ?

**Comment by stfnbrgh** [comment]
@boustanihani - Not at all, see https://github.com/dburles/meteor-collection-helpers/pull/37#issuecomment-108884237. I will push a package called nested-collection-helpers once the code has matured a bit. For now just use it directly from https://github.com/stfnbrgh/meteor-nested-collection-helpers

**Comment by stfnbrgh** [comment]
Published collection-nested-helpers to atmosphere https://atmospherejs.com/stfnbrgh/nested-collection-helpers.

**Comment by boustanihani** [comment]
cool :+1:

**Comment by serkandurusoy** [comment]
I'd also like to see this either as a part of or as an addon to collection helpers

I find myself in need of this functionality, but I have concerns about replacing collection helpers with another package.

**Comment by stfnbrgh** [comment]
I don't have time to work on this at the moment. If you're keen, I'll gladly merge a PR with this functionality.

**Comment by dburles** [comment]
At the moment my thoughts on this are that I don't consider there to be enough value in this feature to justify the extra complexity in the API, it seems needlessly confusing.

It would make most sense to be an addon package if it's going to be sharing the same API (that being a Collection`.helpers` function).
