### ISSUE TITLE
Making helpers available to another collection?

### ISSUE THREAD

**Issue by steph643** [dburles/meteor-collection-helpers#36]
**The issue**

I often mirror collections and I need collection helpers to be transferred from one collection to the other. 

The solution that comes immediately to mind is:
```javascript
MyCollectionB = new Mongo.Collection('myCollectionB', { transform: MyCollectionA._transform });
```

But this solution fails in the following use case:
```javascript
MyCollectionA.helpers({
  next: function() {
    return MyCollectionA.findOne({ order: { $gt: this.order } }, { sort: { order: 1 } });
  }
});
```
Indeed, if I transfer this helper to `MyCollectionB` using the above solution, I get `MyCollectionB::next()` returning an item from `MyCollectionA`!

**What I did to solve the issue**

In `collection-helpers.js`, I have added the following line at the very end:
```javascript
self._helpers.prototype.collection = function() { return self; };
```

Then I do this:

```javascript
SharedHelpers = {
  next: function() {
    return this.collection().findOne({ order: { $gt: this.order } }, { sort: { order: 1} });
  }
};

MyCollectionA.helpers(SharedHelpers);
MyCollectionB.helpers(SharedHelpers);
```

**Any advice on how to improve this?**

**Comment by dburles** [comment]
Hey @steph643 I've decided it's best not to provide an API for this as there's many simple methods you can use to achieve this, here's one example:

```js
_.each([Books, Authors], function(collection) {
  collection.helpers({
    formattedCreatedAt: function() {
      return moment(this.createdAt).format('MMMM Do YYYY, h:mm a');
    },
    formattedUpdatedAt: function() {
      return moment(this.updatedAt).format('MMMM Do YYYY, h:mm a');
    }
  });
});
```

There was a bit of discussion on it early on, see here: https://github.com/dburles/meteor-collection-helpers/issues/3

**Comment by steph643** [comment]
Much cleaner, indeed.

For those landing here, here is what I have finally done, to allow for collectionA to be client/server and collectionB to be client only:
```javascript
SharedHelpers = function(collection) { return {
  next: function() {
    return collection.findOne({ order: { $gt: this.order } }, { sort: { order: 1} });
  }
} };

// File 1
MyCollectionA.helpers(SharedHelpers(MyCollectionA));

// File 2
MyCollectionB.helpers(SharedHelpers(MyCollectionB));
```
