### ISSUE TITLE
_ is not defined

### ISSUE THREAD

**Issue by patrickml** [dburles/meteor-collection-helpers#38]
I am experiencing an odd issue where underscore is not defined. I see that someone else had this issue and you added underscore to the `API.use()` oddly enough I am not getting this error on new projects that I import my core on?

~~~
W20150616-09:33:43.507(-4)? (STDERR) ReferenceError: _ is not defined
W20150616-09:33:43.508(-4)? (STDERR)     at [object Object].Meteor.Collection.helpers (packages/dburles:collection-helpers/collection-helpers.js:17:1)
W20150616-09:33:43.508(-4)? (STDERR)     at packages/bace:core/lib/both/collections/projects.collection.js:180:1
W20150616-09:33:43.509(-4)? (STDERR)     at /Users/patricklewis/Documents/sites/meteor/baceadmin/.meteor/local/build/programs/server/packages/bace_core.js:642:4
W20150616-09:33:43.509(-4)? (STDERR)     at /Users/patricklewis/Documents/sites/meteor/baceadmin/.meteor/local/build/programs/server/packages/bace_core.js:1467:3
W20150616-09:33:43.509(-4)? (STDERR)     at /Users/patricklewis/Documents/sites/meteor/baceadmin/.meteor/local/build/programs/server/boot.js:222:10
W20150616-09:33:43.510(-4)? (STDERR)     at Array.forEach (native)
W20150616-09:33:43.510(-4)? (STDERR)     at Function._.each._.forEach (/Users/patricklewis/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150616-09:33:43.511(-4)? (STDERR)     at /Users/patricklewis/Documents/sites/meteor/baceadmin/.meteor/local/build/programs/server/boot.js:117:5
~~~

**Comment by patrickml** [comment]
Something funky was going on and It seemed to be downloading and using a much older release of this package. I added a version number and everything seemed to work (Whats odd is I deleted all references to this package from ~/.meteor/packages/)

**Comment by dburles** [comment]
Hey @patrickml might there be a package in your project that has a dependency on collection-helpers?

**Comment by patrickml** [comment]
Yeh i created a package called core and part of the core logic depends on your collection helpers package. The issue though was something funky were it was using the really old version of this package I had to delete all versions from the `~/.meteor` folder to fix it. Its happened to me before with another package I think its a bug with the packaging system.

**Comment by lorensr** [comment]
I just got this as well. Package system is designed to use oldest version, so if you have:

```
app/packages/foo/package.js
api.use('dburles:collection-helpers')
```

it will use `v0.1.6`. 

`api.use('dburles:collection-helpers@1.0.0')`

Will use the highest version above v1 that is lower than v2.
