### ISSUE TITLE
How to return a reactive cursor?

### ISSUE THREAD

**Issue by satyavh** [dburles/meteor-collection-helpers#39]
So I'm trying to return a cursor

```
Posts.helpers (->
   comments: ->
     Comments.find belongsToPost: @_id
)
```

Then I call this helper from Template.onCreated: `Posts.comments()` and it does indeed return a cursor. Kind of. Because I can't do anything with the cursor, for example I can't do `Posts.comments().find(belongsToPost: 12)`

So is it possible to return a functional cursor? And more important, is that cursor reactive?

**Comment by dburles** [comment]
Hey @satyavh a cursor is what's returned upon calling a collections' `find` method. collection-helpers are attached to the documents that are returned from a query (they're not class methods). Your `comments` helper looks just fine and you would call it on a document like so: `Posts.findOne().comments()` which will return the comments cursor.

**Comment by satyavh** [comment]
I get that, but if it returns a cursor I'd be able to find a specific comment, right?

`comment = Posts.findOne().comments().find({some query})`

That doesn't seem to work?

**Comment by dburles** [comment]
The mistake that you're making here is that a cursor doesn't have a `find` method itself, unlike a `Collection`. What's the use-case for wanting to query the comments for an individual post?

**Comment by satyavh** [comment]
I see, thanks for pointing that out. I want to find a specific comment but ok, I know how to do that now.

However, suppose more comments get added. Does the helper reactively update?

**Comment by dburles** [comment]
Yep it'll reactively update in any computation as you're returning a cursor.
