### ISSUE TITLE
helpers in document on allow

### ISSUE THREAD

**Issue by Nemo64** [dburles/meteor-collection-helpers#4]
The meteor collection methods to [allow and deny](http://docs.meteor.com/#allow) objects on _update_ and _remove_ give a parameter `doc` which contains the original object before modification. These do not have the helpers attached. Is that fixable?

**Comment by theduke** [comment]
This is still an issue for me with the newest version!

**Comment by dburles** [comment]
You can pass the `doc` object into the transform function like so: `doc = MyCollection._transform(doc);`

**Comment by theduke** [comment]
Good to know, thanks.
Would be good to add this to the Readme.

**Comment by theduke** [comment]
Fair warning to others: after doing doc = Collection._transform(doc),
changes to the new doc will not make it to mongo!

**Comment by dburles** [comment]
Good point. I think there's a good reason that it's not transformed.
