### ISSUE TITLE
Meteor.user helpers with extra fields

### ISSUE THREAD

**Issue by shactdeveloper** [dburles/meteor-collection-helpers#44]
Hello, my Meteor.users is something like this:
```
{
username: {}
services: {}
profile: {}
>>> info <<< : {}
}
```
I have this extra field called info where I store important things about the user
when using a helper in Meteor.users, the object "this" does not have the "Info" field, only username, services, profile...
How can I solve this ?

**Comment by dburles** [comment]
Hey @shactdeveloper are you referring to on the client? If so, you may need to publish that field

**Comment by shactdeveloper** [comment]
```
Meteor.publish(null, function() {
return Meteor.users.find({}, {fields: {empresaId: 1,roles:1}});
});
```

this fixed the problem, thanks!

**Comment by dburles** [comment]
perfect!
