### ISSUE TITLE
Helper to all collections

### ISSUE THREAD

**Issue by shactdeveloper** [dburles/meteor-collection-helpers#45]
Hi! all my collections have a field called createdBy
I would like to create a helper to all my collections to retrieve the user that createdBy is referring to
Can I achieve this with collection-helpers package?

**Comment by dburles** [comment]
Hey @shactdeveloper there's no built in way to achieve this, however here's a nice approach you can use:

```js
[Books, Authors].forEach(function(collection) {
  collection.helpers({
    createdBy: function() {
      return Meteor.users.findOne(this.userId);
    }
  });
});
```
