### ISSUE TITLE
Conflict with tap-i18n-db collection

### ISSUE THREAD

**Issue by Kostanos** [dburles/meteor-collection-helpers#46]
Hi, trying to use helper with tap-i18n-db collection and got this error:

```
Uncaught Error: [Can't apply helpers to 'meals' a transform function already exists!]
```

Any ways to make them compatible?

**Comment by dburles** [comment]
Hey @Kostanos which package is applying the transform function?

**Comment by Kostanos** [comment]
I opened the pull request with fix to this issue. #47

The package is: https://github.com/TAPevents/tap-i18n-db

I'm sure there are many other like this.
