### ISSUE TITLE
Possible conflict with collection2

### ISSUE THREAD

**Issue by thomasspiesser** [dburles/meteor-collection-helpers#51]
hey @dburles ,

I just started with collection-helpers (thanks btw!!!) and experience some weird behavior in combination with the collection2 package, when using its validation method.

I also created a ticket over there: https://github.com/aldeed/meteor-collection2/issues/269 and a clean repo showing the problem https://github.com/thomasspiesser/c2-collection-helper-bug-repro

I am not sure if this is the intended behavior or if this is a bug. 

Any thoughts on this?

**Comment by dburles** [comment]
thanks @thomasspiesser I'll take a look soon

**Comment by dburles** [comment]
Hey @thomasspiesser looks like this issue isn't related to this package but rather collection2, the reason is that applying any transform function to a collection reproduces this behaviour, for example:

```js
Course = function(doc) {
  return _.extend(this, doc);
};

Course.prototype.canEdit = function() {
  return Meteor.userId() === this.owner;
};

Courses = new Mongo.Collection("courses", { transform: function(doc) { return new Course(doc); } });
```

**Comment by thomasspiesser** [comment]
good that you could confirm that @dburles. thanks for taking a look!
