### ISSUE TITLE
Reactive property

### ISSUE THREAD

**Issue by romainkoenig** [dburles/meteor-collection-helpers#53]
Hello,
I am trying to use your package to add property (and methods) to a collection.
I managed to add local property (not persisted in database) with : 

    Budget.helpers({
      show: true,
      toggleShow: function() {
        //console.log(this);
        this.show = !this.show;
        return this.show;
      }
    });

In .html : 

    {{show}} // show always true
     <button id=#triggerShow></button> // call the this.toggleShow() in a event handler

It works, I have the property in the object and the method in the prototype of the objects.
However it did not update the value in the view (HTML) when I trigger the method. I would like to know what I did wrong or if it is possible at all ?

**Comment by dburles** [comment]
Hey @romainkoenig I think this logic should probably just live within the templates between template helpers and events on not be a collection-helper, however if there's some reason that you may need to use this function outside of the templates then what you're probably looking for is a `ReactiveVar`.

```js
Budget.helpers({
  show: ReactiveVar(true),
  toggleShow: function() {
    //console.log(this);
    this.show.set(!this.show.get());
    return this.show;
  }
});
```

Don't forget to `meteor add reactive-var`

**Comment by romainkoenig** [comment]
Thank you for your response ! I also agree that this logic has to be in the template. However I had this problem of a long list of a collection to display. And I wanted to add more information to each element. meteor-collection-helpers is great because I can add computed variable from the ones I already have in the collection, but I also wanted to add state only in the scope of this Session. Show/hide things, just to add UI stuff reactively to each element of the list. Whereas i use ReactiveVar on the template to add global UI element like Show/Hide this form element. I will try you solution and continue my investigations !
