### ISSUE TITLE
custom helper keeps returning same document

### ISSUE THREAD

**Issue by craigmacgregor** [dburles/meteor-collection-helpers#54]
I'm using meteor-admin combined with meteor-collection-helpers to try and display a custom helper within the 'view all' view of my collection.

I have two collections; artists and artistImages. artistImages are linked to an artists with their _id. That works fine and I have the correct artists name displaying in my dropdown in the edit/new screen of artistImages. I want the artist's name to display in the 'view all' section of the artistImages collection against each row, but for some reason its always the first artists name which displays.

In my meteor-admin config file I have the collection setup like this:

```javascript
...
ArtistImages: {
    tableColumns: [
        { label: 'ArtistId', name: 'artistId' },
        { label: 'Artist', name: function() {
                return ArtistImages.findOne().artist();
            }
        },
        { label: 'Image', name: 'image' },
    ]
},
...
```
Then inside my artistImages collection definition I have

```javascript
ArtistImages = new Mongo.Collection("artist-images");

ArtistImages.helpers({
    artist: function() {
        var artist = Artists.findOne(this.artistId);
        if(artist){
            return artist.name;
        } else {
            return "(undefined)";
        }
    }
});

Schemas = {};

Schemas.ArtistImages = new SimpleSchema({
    artistId: {
        type: String,
        label: 'Artist',
        autoform: {
            options: function () {
                return _.map(Artists.find({}).fetch(), function (artist) {
                    return {
                        label: artist.name,
                        value: artist._id
                    };
                });
            }
        }
    },
    image: {
        type: String,
        label: 'Image',
        max: 200,
        optional: true
    },
    caption: {
        type: String,
        label: 'Caption',
        max: 120,
        optional: true
    }
});

ArtistImages.attachSchema(Schemas.ArtistImages);
```

However if i console.log this.artistId from within the artist() helper, its always returning the same id even if i have different artists assigned to each artist image.

view all:

<img width="595" alt="screen shot 2015-11-21 at 1 58 59 pm" src="https://cloud.githubusercontent.com/assets/6902746/11315522/1a3d4354-9058-11e5-927e-3389f0542e6c.png">

Notice the artistId is different but the name is the same, both names are for the artist in the first row.

Any suggestions? I'm stumped.

**Comment by dburles** [comment]
Hey seems most likely to do with the way the admin package generates the rows, I'd suggest opening an issue over there

**Comment by craigmacgregor** [comment]
cool as, i thought it probably was. What I'm doing with the collection helpers seems correct but its just getting the wrong data through for the row. I've duplicated the issue over there. 

Thanks for the reply! I'll report back when I manage to fix the problem

**Comment by craigmacgregor** [comment]
It seems like the document is passed into the function in the meteor-admin configuration like this:

```javascript
...
ArtistImages: {
    tableColumns: [
        { label: 'ArtistId', name: 'artistId' },
        { label: 'Artist', name: function(doc) {
                return ArtistImages.findOne({_id: doc._id}).artist();
            }
        },
        { label: 'Image', name: 'image' },
    ]
},
...
```
The rest of the code is correct, this fixes the issue. Pity its not documented, I just had a brainwave, tried it and it worked!

**Comment by dburles** [comment]
Oh that's good @craigmacgregor! Also, I'd probably name that helper `artistName` instead and have `artist` simply `return Artists.findOne(this.artistId);`
