### ISSUE TITLE
Big data

### ISSUE THREAD

**Issue by proft** [dburles/meteor-collection-helpers#55]
Hello! Thanks for this package!

I have big data (~100000 documents). I publish first 100 and then +100 on every request. 

Documents have relations with other collections. I use helpers like this

```
City.helpers
    countryObj: ->
        Country.findOne({_id: this.country}) 
```

So I publish 100 items and list related fields in table ({{ countryObj.title }}). It is empty, because I published few of them (of ~100000). When I request next part empty fields get data ...

Is it possible load related fields without waiting?

**Comment by dburles** [comment]
Hey @proft unless I'm misunderstanding you it sounds like it's a publication or denormalisation problem you're having.

**Comment by proft** [comment]
Hi! Thanks for article! I mean 'Publish with relations' :)
