### ISSUE TITLE
[question] Are helpers secure?

### ISSUE THREAD

**Issue by trusktr** [dburles/meteor-collection-helpers#56]
Can I use them instead of Methods? For example:

```js
import Schema from './Schema'

const Buckets = new Mongo.Collection('Buckets')
export default Buckets
Object.freeze(Buckets)

new Schema({
    things: [String],
}).applyTo(Organizations)

// helpers?
Buckets.helpers({
    addThing(thing) {
        Buckets.update(this._id, {$push: {things: thing}})
    },
})

// or methods?
Meteor.methods({
    ['Buckets.addThing'](bucketId, thing) {
        Buckets.update(bucketId, {$push: {things: thing}})
    }
})

// ...

bucket.addThing({foo:'bar'}) // cleaner!
// or
Meteor.call('Buckets.addThing', bucket._id, {foo:'bar'}) // more secure?
```

The helper version is nice, but is it secure like Methods are? Do they get executed as Methods behind the scenes? If not, that would be an interesting feature to add.

**Comment by dburles** [comment]
Hey @trusktr there's nothing inherently special about helpers, they're just prototypes. To answer your question though, methods and helpers are two completely different things. It would make more sense to consider calling your `addThing` helper within a method itself. See here for more detail on writing methods: http://guide.meteor.com/methods.html

**Comment by trusktr** [comment]
@dburles True, and I thought of that. But, as you can see, the helper methods are shorter and cleaner. I might try rolling some method-based ones.

**Comment by dburles** [comment]
The main problem with the helper doing mutations is that if you call it on the client you'll have to make use of allow/deny rules over writing an explicit method (which is preferred as there's talk of possibly even deprecating allow/deny).
