### ISSUE TITLE
Helpers are undefined with flow-router-ssr

### ISSUE THREAD

**Issue by chmac** [dburles/meteor-collection-helpers#60]
We're seeing this error with flow-router-ssr:

    Error when doing SSR. path:/foo/bar: Object [object Object] has no method 'baz'

Doing some debugging, it looks like the helpers are not defined on the server. I guess the issue is that the SSR code does some magic to "wrap" collections, and then the helper code doesn't get applied. So the issue is probably not in this package, but wondering if anyone has a workaround or a fix?

**Comment by dburles** [comment]
Hey @chmac a possible work around may be to apply the helpers manually https://github.com/dburles/meteor-collection-helpers#applying-the-transformation-function

**Comment by klarstrup** [comment]
I've had success with using the transformation function myself.

**Comment by chmac** [comment]
@dburles: Yes, that is the sensible workaround, which I eventually figured out, after thinking about this for a few weeks! :-) Although using the transform function is smart, I was manually instantiating with `new Collection._helpers(doc)`. I'll change that.

Any advice on how to test if the helper have been applied? I guess the transform is not idempotent. I'm currently using `doc instanceof Collection._helpers`, but maybe there's a better way?

Oh, and I forgot to say, thanks for sharing this package, it's remarkably useful, has changed the way we approach code structure.

**Comment by dburles** [comment]
Thanks @chmac and yes that's the best way to test if they have been applied!

**Comment by chmac** [comment]
Would there be any sense in adding the rest into the transform function so it becomes idempotent? Feels somehow like the wrong approach to me, but at the same time, not sure if there would be any harm. I'd be happy to try and whip up a PR if you think it'd be useful, but equally happy if you don't.

**Comment by dburles** [comment]
@chmac not sure what you mean exactly, got an example?

**Comment by chmac** [comment]
I was thinking the `_transform` would become something like:

    self._transform = function(doc) {
      return doc instanceof self._helpers ? doc : new self._helpers(doc);
    };

It wouldn't necessarily have to be a one liner, but that was quicker to type in here! Essentially the idea is that we could call `Collection._transform(doc)` multiple times, and the second and subsequent times would have no effect. Would mean that in my current situation, instead of having to check the `instanceof`, I could just add a manual call to the `_transform()`.

The underlying thought here, is that if the package changes it's architecture somehow, then my test `doc instanceof Collection._helpers` may fail in the future, and we won't immediately know why. While if the test itself was part of the package, then hopefully any future changes would also change the test.

**Comment by dburles** [comment]
Hmm I see what you're saying. Though I wonder why do you think we should avoid applying the helpers more than once?

**Comment by chmac** [comment]
Hahaha, you make an excellent point! Maybe applying them multiple times is actually the absolutely simple option that I missed! Somehow I instinctively had the idea that passing a `Document` rather than an `Object` to the `_transform` was a bad idea, but now that you quesrion that, I can't think of a good reason... :-)

**Comment by dburles** [comment]
Yeah I think it's totally fine, and hopefully they'll be a fix for flow-router so that you don't have to bother with the workaround :)

**Comment by chmac** [comment]
Makes sense. Thanks for the help.

I'll close this and wait on flow SSR adding support for `_transform()`.
