### ISSUE TITLE
Subscription and Publishing

### ISSUE THREAD

**Issue by humbertocruz** [dburles/meteor-collection-helpers#61]
Hello,

I have a few users and "stamps" associated to each of them. I did a collection-helper on collection users that show the quantity of stamps of each user but I had to publish all stamps. There is any better way to do that ?

Thanks

**Comment by dburles** [comment]
Hey check out the tmeasday:publish-counts package

**Comment by humbertocruz** [comment]
I know this package but I did not understand how to use it to solve this problem. My "stamps" collection is very large and would be greate every day. I just do not want to publish and subscribe all of the only for show the quantity for each user.

**Comment by dburles** [comment]
I think in that case you'll most likely want to denormalise the total onto the user document each time the a stamp is added or removed.

**Comment by dburles** [comment]
Here's a good write up on just that http://guide.meteor.com/collections.html#abstracting-denormalizers

**Comment by humbertocruz** [comment]
ok.. this works for this case... but when I need all the documents related for one user. I'm still having to publish/subs all "stamps". Maybe do a subscription in the "collection helper" passing the userId ?

**Comment by dburles** [comment]
You might be best to ask on stackoverflow as here is really suited for bugs and feature requests for the package

**Comment by humbertocruz** [comment]
ok. sorry, i'm looking for but no luck on this...

**Comment by dburles** [comment]
Also the (Meteor forums)[https://forums.meteor.com/] would be a great place to get help

**Comment by humbertocruz** [comment]
I found a solution, use reywood:publish-composite together with collection-helpers than I need to subscribe only the top level and the other collections will be availabe.
