### ISSUE TITLE
TypeError: <Collection>.helpers is not a function when running package tests

### ISSUE THREAD

**Issue by francisbyrne** [dburles/meteor-collection-helpers#70]
@dburles I'm having trouble running package tests for files with e.g. `MyCollection.helpers` referenced. The app runs fine, but the tests fail with the following error:

`TypeError: MyCollection.helpers is not a function`

I've created a repo to demonstrate the issue:

https://github.com/francisbyrne/helpers-test/tree/master

To reproduce, run this command in the root dir of the repo:

`meteor test-packages lookback:teams --driver-package dispatch:mocha`

**Comment by dburles** [comment]
Hey @francisbyrne the problem you've encountered there is that you need to specify the version of the package that you wish to use, `versionsFrom` only covers core packages. https://github.com/francisbyrne/helpers-test/pull/1

**Comment by francisbyrne** [comment]
@dburles Ah, thanks for clearing that up. I can confirm it works on my machine/project as well. Out of interest, why does one have to specify the package versions, rather than let the version solver pick the optimal one?

**Comment by dburles** [comment]
Yeah it's a bit weird, there's an open issue on it here with details on what's happening https://github.com/meteor/meteor/issues/4170

**Comment by francisbyrne** [comment]
Awesome, thanks for the context @dburles! I'll take a look and close this issue 👍
