### ISSUE TITLE
printing the complete function on to the console instead of returning the value

### ISSUE THREAD

**Issue by naveenkonduru** [dburles/meteor-collection-helpers#71]
Hello,

I am using reactjs as my frontend framework. when I tried to access helper method , it is just printing the complete function on to the console instead of returning the value. 

Am I missing something here.. ?

const Friends = new Mongo.Collection('friends');
Friends.helpers({
    fullName() {
        return "First Last";
    }
});

Client Side code:
============

var response = Friends.find().fetch()
response.map(function(row){
   console.log(row.fullName);
});

Console output:
===========
fullName() {   
// 5
    return "First Last";
...

**Comment by naveenkonduru** [comment]
Here is the fix
response.map(function(row){
var name  = row.fullName;
console.log(name());
});

**Comment by dburles** [comment]
Yeah the problem you're having is that `fullName` is a function and in the first example you're not executing it. `row.fullName()`
