### ISSUE TITLE
Meteor helpers with fetch

### ISSUE THREAD

**Issue by jdnichollsc** [dburles/meteor-collection-helpers#74]
Hi guys,

Thanks for this project! One question, exist any example using *fetch*? For example

```
var myArray = myCollection.find({}).fetch();
myArray[0].myHelperProperty(); //Doesn't exist...
```

Thanks in advance, Nicholls

**Comment by dburles** [comment]
Hey @jdnichollsc that should work just fine, the most likely cause is that the helpers haven't been applied to the collection that you're querying. Perhaps you defined them only on the server (or client).

**Comment by jdnichollsc** [comment]
Hi man, thanks for your quickly response! 
Exist any example? I'm using publications in the server side.

Regards, Nicholls

**Comment by dburles** [comment]
What I mean is that you'll want to be sure that you have defined your helpers where you are expecting to use them. Can you provide a link to a repo with a very simple reproduction of your issue?

**Comment by jdnichollsc** [comment]
Sorry @dburles, this project works like a charm! 👍
