### ISSUE TITLE
Collection.helpers are not defined

### ISSUE THREAD

**Issue by BendaCoding** [dburles/meteor-collection-helpers#76]
Hi,
im having issues getting the helpers to work on a collection.
Regular queries are working just fine, but when i try to access a helper function it throws an error:
**Uncaught TypeError: *Collection.method* is not a function**

*excerpt of my RegisterPage Container:*
```
import { Settings } from '../../../lib/api/settings.js'

class RegisterPage extends Component {
render() { ... }
}
export default createContainer(() => {

    const settingsHandle = Meteor.subscribe('settings')

    return {
        loading: ! settingsHandle.ready(),
        min: Settings.findOne({name: 'min'}), // this is working fine
        Range: Settings.getRange() // throwing error
    }
}, RegisterPage)
```

*collection with helper definition inside lib/api/settings.js:*
```
export const Settings = new Mongo.Collection('settings');

Settings.helpers({
    getRange() {
        const Range = Settings.find( {name: { $in: ['min', 'max'] }).fetch()
        return Range
    }
})
```

Any ideas what might cause the issue?
Im on the current release 1.1.0

**Comment by dburles** [comment]
Hey @BendaCoding collection helpers applies instance methods to documents returned from queries, they're not class methods

**Comment by zhanbst** [comment]
I think need to close issue!
ex. 
`
Settings.findOne({name: 'min'}).getRange()
`

**Comment by BendaCoding** [comment]
okay thanks anyways. i ended up defining them on a global Helpers class
