### ISSUE TITLE
Issues with collection helpers on Meteor 1.5?

### ISSUE THREAD

**Issue by ccuilla** [dburles/meteor-collection-helpers#81]
I'm still investigating this, just testing my app on Meteor 1.5...but it's looking like collection helpers are not getting added in Meteor 1.5.

I'm going to try and isolate this and create a re-pro example, but I'm just wondering if anyone has seen this?

ADDITIONAL DETAIL: I'm trying to use these inside Apollo resolver functions on the server side.

**Comment by ccuilla** [comment]
I'm going to close this because I'm not sure it's an issue with the `meteor-collection-helpers` package.

But be aware that the `user` delivered in `context` to Apollo resolver functions has **_not_** had the collection helpers added to it. At least something has changed in Meteor 1.5 that is causing this change.

**Comment by dburles** [comment]
@ccuilla interesting, you can always manually apply helpers too if required, https://github.com/dburles/meteor-collection-helpers#applying-the-transformation-function

**Comment by ccuilla** [comment]
@dburles Thanks for that reminder. I'll try that.
