### ISSUE TITLE
attach helpers to rawCollection?

### ISSUE THREAD

**Issue by niklasdahlheimer** [dburles/meteor-collection-helpers#86]
Hey,
First of all: great package! It saved me a lot of time copying redundant code between react components!

I run in a situation where I need to use the rawCollection instead of the Meteor.Collection (i.e. to do some efficient fullText-search). Obviously the helpers are not defined as prototypes for results from a rawCollection query. 
Is there a way to use the helpers in the rawCollections too?

Please reply if my question is clear or if I should add a code example

greetings!

**Comment by dburles** [comment]
Thanks @niklasdahlheimer! all you need to do is apply the helpers to the object, see this example: https://github.com/dburles/meteor-collection-helpers#applying-the-transformation-function

**Comment by niklasdahlheimer** [comment]
Thanks @dburles, that works for single objects pretty well but I can't make it work with a Meteor collection as param in a function.

```
function searchWithRegEx(meteorCollection, searchString) {
    return meteorCollection.rawCollection()
        .find({"someKey": new RegExp(searchString, "gi")})
        .toArray()
        .then(array => array.map(result => meteorCollection._transform(result)));
};
```

Any idea on this? Thanks!

**Comment by dburles** [comment]
That should result in the methods being applied to each object. However, looking at the use of an arrow function it's likely that calling methods that refer to `this` might not be correctly referring to the object itself.

**Comment by niklasdahlheimer** [comment]
I tried

1. replace the arrow functions with ordinary functions
```
function searchWithRegEx(meteorCollection, searchString) {
    return meteorCollection.rawCollection()
        .find({"someKey": new RegExp(searchString, "gi")})
        .toArray()
        .then(function (array) {
            array.map(function (result) {
                meteorCollection._transform(result)
            })
        });
};
```
2.  using call() to pass the collection explicitly as the `this` object
```
...
meteorCollection._transform.call(meteorCollection, result);
...
```

None of that helped. 
When I log the passed meteorCollection by calling
`console.log(meteorCollection)`
it prints out: 
```
SomeCollection {
...
_helpers: [Function: Document]
...
}
```

So it looks like the helper functions are attached to it. Probably I still have a false understanding of the `this` keyword, I'm pretty confused why it's not returning the transformed result correctly.

**Comment by niklasdahlheimer** [comment]
I made some progress on this.

It turns out that `meteorCollection._transform(result)` indeed adds the correct helpers as prototypes! 
The problem is, that my function lives inside a Meteor method (which of course runs serverside) and the results are passed via an async callback-function to the client **and that is where the helpers disappear**

- calling `Object.getPrototypeOf(myObj) `in the Meteor method -> helpers are **available**
- calling `Object.getPrototypeOf(myObj)` in the callback function inside the Meteor.call -> helpers are **gone**, only default prototypes are shown (`constructor`, `hasOwnProperty`,..)

I searched around in the Meteor API reference and Meteor guide but could not find anything related to this issue. Could it be that these helper-methods are not serializable and are thrown away when Meteor passes the results to the client?

**Comment by dburles** [comment]
@niklasdahlheimer Ah I see, yeah that makes sense. That's right, it's just a serialised object being sent across. In that case just apply the helpers to the document returned from the method on the client.

**Comment by niklasdahlheimer** [comment]
Yes. I will have to do the transformation at a lot of places because the serverside function was meant to be "generic", but there seems to be no other work around.
Because it's likely anothers will stumble across this problem, I would suggest a little note/hint in the Git Readme, but it's yours to decide if it's common knowledge that prototypes are not serializable and couldn't be passed over the wire :)
